/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BecomeAVendorRouteImport } from './routes/become-a-vendor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as VendorDashboardRouteImport } from './routes/vendor-dashboard'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAVendorRoute = BecomeAVendorRouteImport.update({
  id: '/become-a-vendor',
  path: '/become-a-vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor-dashboard',
  path: '/vendor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/become-a-vendor': typeof BecomeAVendorRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/services': typeof ServicesRoute
  '/vendor-dashboard': typeof VendorDashboardRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/become-a-vendor': typeof BecomeAVendorRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/services': typeof ServicesRoute
  '/vendor-dashboard': typeof VendorDashboardRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/become-a-vendor': typeof BecomeAVendorRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/services': typeof ServicesRoute
  '/vendor-dashboard': typeof VendorDashboardRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/become-a-vendor'
    | '/dashboard'
    | '/explore'
    | '/how-it-works'
    | '/login'
    | '/plan'
    | '/services'
    | '/vendor-dashboard'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/become-a-vendor'
    | '/dashboard'
    | '/explore'
    | '/how-it-works'
    | '/login'
    | '/plan'
    | '/services'
    | '/vendor-dashboard'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/become-a-vendor'
    | '/dashboard'
    | '/explore'
    | '/how-it-works'
    | '/login'
    | '/plan'
    | '/services'
    | '/vendor-dashboard'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BecomeAVendorRoute: typeof BecomeAVendorRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PlanRoute: typeof PlanRoute
  ServicesRoute: typeof ServicesRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-vendor': {
      id: '/become-a-vendor'
      path: '/become-a-vendor'
      fullPath: '/become-a-vendor'
      preLoaderRoute: typeof BecomeAVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-dashboard': {
      id: '/vendor-dashboard'
      path: '/vendor-dashboard'
      fullPath: '/vendor-dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BecomeAVendorRoute: BecomeAVendorRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PlanRoute: PlanRoute,
  ServicesRoute: ServicesRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
